/*
* Generated file
*
* Generated from: yang module name: sfc-netconf-impl yang module local name: sfc-netconf-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Dec 17 19:23:09 CST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.sfc_netconf.impl;
public interface SfcNetconfModuleMXBean {
    public javax.management.ObjectName getDataBroker();

    public void setDataBroker(javax.management.ObjectName dataBroker);

    public javax.management.ObjectName getBindingRegistry();

    public void setBindingRegistry(javax.management.ObjectName bindingRegistry);

}
