/*
* Generated file
*
* Generated from: yang module name: sfc-l2renderer-impl yang module local name: sfc-l2renderer-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Dec 17 19:22:26 CST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.sfc_l2renderer.impl;
public interface SfcL2RendererModuleMXBean {
    public javax.management.ObjectName getRpcRegistry();

    public void setRpcRegistry(javax.management.ObjectName rpcRegistry);

    public javax.management.ObjectName getDataBroker();

    public void setDataBroker(javax.management.ObjectName dataBroker);

    public javax.management.ObjectName getNotificationService();

    public void setNotificationService(javax.management.ObjectName notificationService);

}
