/*
* Generated file
*
* Generated from: yang module name: sfc-vnfm-tacker yang module local name: sfc-vnf-tacker-provider
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Dec 17 19:23:16 CST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.sfc.vnfm.tacker;
public interface TackerManagerModuleMXBean {
    public java.lang.String getSfcVnfmTackerTenant();

    /**
    * This is the tenant name used for tacker.
    */
    public void setSfcVnfmTackerTenant(java.lang.String sfcVnfmTackerTenant);

    public java.lang.String getSfcVnfmTackerName();

    /**
    * This is the username used for authentication with tacker service.
    */
    public void setSfcVnfmTackerName(java.lang.String sfcVnfmTackerName);

    public java.lang.Integer getSfcVnfmTackerPort();

    /**
    * This is the port that Tacker uses for communication.
    */
    public void setSfcVnfmTackerPort(java.lang.Integer sfcVnfmTackerPort);

    public java.lang.String getSfcVnfmUri();

    /**
    * This is the URI used for communication with services.
    */
    public void setSfcVnfmUri(java.lang.String sfcVnfmUri);

    public java.lang.Integer getSfcVnfmKeystonePort();

    /**
    * This is the port that Keystone uses for communication.
    */
    public void setSfcVnfmKeystonePort(java.lang.Integer sfcVnfmKeystonePort);

    public java.lang.String getSfcVnfmTackerPassword();

    /**
    * This is the password used for authentication with tacker service.
    */
    public void setSfcVnfmTackerPassword(java.lang.String sfcVnfmTackerPassword);

}
