/*
* Generated file
*
* Generated from: yang module name: sfc-test-consumer-impl yang module local name: sfc-test-consumer
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Dec 17 19:21:28 CST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.sfc_test_consumer.impl;
@org.opendaylight.controller.config.api.annotations.ServiceInterfaceAnnotation(value = "(urn:opendaylight:params:xml:ns:yang:controller:config:sfc-test-consumer:impl?revision=2014-07-01)sfc-test-consumer", osgiRegistrationType = org.opendaylight.sfc.sfc_test_consumer.SfcTestConsumer.class, namespace = "urn:opendaylight:params:xml:ns:yang:controller:config:sfc-test-consumer:impl", revision = "2014-07-01", localName = "sfc-test-consumer")

@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(namespace = "urn:opendaylight:params:xml:ns:yang:controller:config:sfc-test-consumer:impl", revision = "2014-07-01", name = "sfc-test-consumer-impl")

public interface SfcTestConsumerServiceInterface extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface {

}
