/*
* Generated file
*
* Generated from: yang module name: sfc-vnf-manager-cfg yang module local name: sfc-vnf-manager
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Dec 17 19:23:14 CST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.sfc.vnfm.spi;
/**
* Service representing a SfcVnfManager.
*/
@org.opendaylight.controller.config.api.annotations.Description(value = "Service representing a SfcVnfManager.")

@org.opendaylight.controller.config.api.annotations.ServiceInterfaceAnnotation(value = "(urn:opendaylight:params:xml:ns:yang:controller:config:sfc:vnfm:spi?revision=2015-12-07)sfc-vnf-manager", osgiRegistrationType = org.opendaylight.sfc.vnfm.spi.SfcVnfManager.class, namespace = "urn:opendaylight:params:xml:ns:yang:controller:config:sfc:vnfm:spi", revision = "2015-12-07", localName = "sfc-vnf-manager")

@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(namespace = "urn:opendaylight:params:xml:ns:yang:controller:config:sfc:vnfm:spi", revision = "2015-12-07", name = "sfc-vnf-manager-cfg")

public interface SfcVnfManagerServiceInterface extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface {

}
